### ISSUE TITLE
Autoload problem

### ISSUE THREAD

**Issue by arjanvaneersel** [krolow/Attach#26]
I'm having a problem with the plugin, this is the error I get:  "We could not autoload imagine, please set the PSR-0 autoload"

This is caused by [this code](https://github.com/krolow/Attach/blob/develop/Model/Behavior/UploadBehavior.php#L667-L681):

public function getImagine(Model $model) {
        if (!interface_exists('Imagine\Image\ImageInterface')) {
            if (is_file(APP . 'Vendor' . 'autoload.php')) {
                require APP . 'Vendor' . 'autoload.php';
            }

```
        throw new RuntimeException('We could not autoload imagine, please set the PSR-0 autoload');
    }
```

First I had to correct 'RuntimeException', as in the original plugin code there is a typo instead of RuntimeException it has RuntimeExpcetion. You might want to change that.

Despite that, I don't understand the error I get. I have run composer, autoload.php is there, I have no idea what means "set the PSR-0 autoload".

What should I do?

**Comment by sams** [comment]
For me loading the plugin via composer I get no juice loading imagine. 

same message `We could not autoload imagine, please set the PSR-0 autoload`

**Comment by krolow** [comment]
hey guys i'vent been using this code for more than 2 years, if someone want to keep this code uptated let me know... i can allow access to code in repository! cheers!

**Comment by sams** [comment]
I am looking into reworking this though I may focus on cake 3. This is almost exactly what I had in mind (almost)  if I make progress of value I'll let you know

**Comment by waldemarnt** [comment]
:+1: for cake 3
